# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EduwebParents' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EduwebParents
  pod 'React', :path => '../node_modules/react-native', :subspecs => [

    'Core',
    'RCTText',
    'RCTImage',
    # 'DevSupport',
    # 'BatchedBridge',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
    ]

  target 'EduwebParentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
